name: Push-to-Forest

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to run this workflow via external webhook trigger
  repository_dispatch:
    types:
      - webhook

jobs:
  # The `push` job adds a new commit to the repo's branch that is connected to Forest 
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: production

      - name: setup git config
        run: |
          git config user.name "GitHub Forest bot"
          git config user.email "<>"

      - name: commit
        run: |
          git commit --allow-empty -m ":seedling: Triggering deploy on Forest.host :rocket:" 
          git push origin production
