name: Push-to-Forest

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # The `push` job adds a new commit to the repo's branch that is connected to Forest 
  push:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: production

      - name: setup git config
        run: |
          git config user.name "GitHub Forest bot"
          git config user.email "<>"

      - name: commit
        run: |
          git commit --allow-empty -m "Update content. Triggering deploy on Forest.host :rocket:" 
          git push origin production
